# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Smart Living HG About Us
email: alex@designbymodus.com
description: > # this means to ignore newlines until "baseurl:"
  This page is a prototype for the eventual About Us section of smartlivinghg.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://192.168.1.110/~Alex/jekyll/smartliving_about_us/_site" # the base hostname & protocol for your site
twitter_username: alexkademan
github_username:  alexkademan

# Build settings
markdown: kramdown
