# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 2101 Atlantis
email: jennifer@designbymodus.com
description: > # this means to ignore newlines until "baseurl:"
  This page is a prototype for the eventual live website to promote a rental condo in the Bahamas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://192.168.1.110/~Alex/jekyll/abacos/_site" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
